apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap25
  namespace: aap
spec:
  # Platform
  image_pull_policy: IfNotPresent
  # Components
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    ## Modify to contain your RWM storage class name
    # storage_type: file
    # file_storage_storage_class: ocs-external-storagecluster-cephfs
    # file_storage_size: 10Gi

    ## uncomment if using S3 storage for Content pod
    storage_type: S3
    object_storage_s3_secret: autohub-s3

    ## uncomment if using Azure storage for Content pod
    # storage_type: azure
    # object_storage_azure_secret: azure-secret-name
  lightspeed:
    disabled: true