---
  - hosts: all
    tasks:

    - name: add label to existing namespace
      kubernetes.core.k8s:
        state: patched
        kind: VirtualMachine
        name: testvm
        namespace: default
        definition:
          spec:
            template:
              spec:
                domain:
                  memory:
                    guest: 5Gi