---
  - hosts: all
    tasks:

    - name: Create an OCP project
      redhat.openshift.k8s:
        state: present
        resource_definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: testing